### ISSUE TITLE
App isolation isn't working in Node

### ISSUE THREAD

**Issue by kdzapp** [RainwayApp/rainway-sdk-node-examples#10]
Hey all -- didn't see a template for issues so just going to provide a bit of info, let me know if you all need more.

Running this node example on a Windows 2022 server and `RainwayStreamType.FullDesktop` works great, but once I modify the stream type to `RainwayStreamType.AppIsolation` and provide a PID (verified via task manager that I'm providing the correct PID), the stream doesn't show anything. I've also verified that the stream connection is established because the message data is echoed back.

Any help would be great!

**Comment by bengreenier** [comment]
Hi @kdzapp I've just confirmed this is a bug - thanks for helping us find it! 😅 

We're already planning to ship a new `0.4.0-beta.2` build in the next few days, and will include a fix for this in that release. In the meantime, it's possible to manually patch our sdk to resolve this issue, i've included the steps to do so below. After applying the change, `isolateProcessIds` should be properly marshalled to the native Rainway SDK component, that does the actual isolation. Hope that helps!

- Clone this project
- npm install
- In `node_modules\rainway-sdk-native\dist\index.js` make the following change

> Note: Running `npm install` again may overwrite this change

Change line 406 from:
```
isolateProcessIds: isolateArr.ref(),
```

to:
```
isolateProcessIds: isolateArr.buffer,
```

In case line numbers don't line up for some reason (they should) this is part of the following definition:
```
const rawConfig = new librainway_1.RainwayStreamConfigDef({
                streamType: config.streamType,
                inputLevel: config.inputLevel,
                incomingInputFilter: inputFilterCallback,
                isolateProcessIds: isolateArr.ref(),
                isolateProcessIdsCount: (_e = (_d = config.isolateProcessIds) === null || _d === void 0 ? void 0 : _d.length) !== null && _e !== void 0 ? _e : 0,
            });
```

**Comment by kdzapp** [comment]
Great! Thank you for the fix -- confirming this worked for me.
