### ISSUE TITLE
Keyboard input not sending for ^0.4.0-beta.2

### ISSUE THREAD

**Issue by kdzapp** [RainwayApp/rainway-sdk-node-examples#12]
Per the title, it seems after moving over to the new package `@rainway/native` version `0.4.0-beta.2` the keyboard input is not being sent to the server.

**Comment by emily33901** [comment]
Hi, I reproduced this just now, and a fix should be out by next update.

For now you can prevent default on the event in the stream input event listener, which will actually then cause the events to be passed to the host.
```ts
      const stream = await req.accept({ ... });
      stream.addEventListener("input", (ev) => { ev.preventDefault(); });
```
