### ISSUE TITLE
 No such file or directory rainwaysdk.so

### ISSUE THREAD

**Issue by oksanassss** [RainwayApp/rainway-sdk-node-examples#16]
I tried run it but ı'm getting this error.
```
Error: ENOENT: no such file or directory, open '/home/ozan/rainway/rainway-sdk-node-examples/host-example/node_modules/@rainway/native/native/rainwaysdk.so'
```
ı runned ```npm run build ``` but ı have not got  ```rainways.so``` in node_modules so ı can't run host example.

**Comment by lynn** [comment]
Hi, did you run `npm install`?

**Comment by bengreenier** [comment]
This looks like you may be trying to use the node sdk on a non windows machine - We only support windows at this time.

**Comment by oksanassss** [comment]
yes ı tried linux. Thanks. :+1:
